/**
 * omp-overlay.ts — Write the omp config overlay for a Fcode session (T15).
 *
 * The overlay is a YAML file merged by omp after its global and project
 * settings (--config <path> flag). It sets:
 *
 *   skills.customDirectories   — bundled Frappe skill pack
 *   skills.enableClaudeUser    — load user's ~/.claude/skills as well
 *   tools.approval             — per-tool prompt policy
 *   browser.*                  — browser integration settings
 *
 * **Security note (plan §CEO accepted #4, DX adjudication):**
 * The overlay does NOT set `approvalMode: yolo`. The global mode is set via
 * `--approval-mode always-ask` at spawn time. The `tools.approval` map below
 * suppresses prompts only for read-only introspection calls (a footgun guard,
 * not a security boundary — omp's bash tool can still run bench regardless).
 * State-changing verbs remain gated behind always-ask.
 *
 * **Fatal on write failure (plan §DX X11):**
 * If this file cannot be written, omp spawns WITHOUT the overlay, which
 * means it falls back to its own schema default (`yolo`), silently auto-
 * approving every write and exec. That is unacceptable. `writeOmpOverlay`
 * therefore throws on any write error; the caller must NOT start omp if this
 * rejects.
 *
 * **Debug tracing:**
 * Set `FCODE_BRIDGE_TRACE=1` in the environment before launching Fcode to
 * write raw omp RPC frames to `<dataDir>/bridge-trace.ndjson`.
 */
import { writeFile } from "node:fs/promises";
import { join } from "node:path";

/**
 * Build the YAML overlay string from the given paths.
 *
 * @param resourcesPath - Electron `process.resourcesPath` (contains fcode-skills).
 * @param dataDir       - Fcode's data directory (writable, session-specific).
 */
function buildOverlayYaml(resourcesPath: string, dataDir: string): string {
  // Inline YAML template — no YAML serialisation library needed for a static shape.
  return `# Fcode omp configuration overlay
# Generated by omp-overlay.ts — do not edit by hand.
# This file is written fresh on every omp spawn and overrides global/project settings.

# ── Skills ────────────────────────────────────────────────────────────────────
skills:
  # Load the bundled Frappe skill pack from extraResources/fcode-skills.
  customDirectories:
    - "${join(resourcesPath, "fcode-skills")}"
  # Also load skills from ~/.claude/skills if the user has a private Frappe library.
  enableClaudeUser: true

# ── Per-tool approval policy ───────────────────────────────────────────────────
# Global approval mode is set via --approval-mode always-ask at spawn time.
# This map suppresses prompts only for read-only introspection (footgun guard).
# State-changing verbs (fcode_bench_run migrate, install-app, etc.) still prompt.
#
# FCODE_BRIDGE_TRACE=1 — set this env var to write raw omp RPC frames to:
#   ${join(dataDir, "bridge-trace.ndjson")}
tools:
  approval:
    # Auto-approve read-only bench introspection.
    # The bridge's prefix matcher enforces read-only methods before this policy
    # takes effect; mutating methods fall through to always-ask regardless.
    fcode_bench_execute: allow
    # always-ask for state-changing bench commands (migrate, install-app, …)
    fcode_bench_run: always-ask
    # Read-only canvas actions (snapshot/console/screenshot) need no prompt.
    fcode_canvas_read: allow

# ── Browser integration ────────────────────────────────────────────────────────
browser:
  enabled: true
  headless: true
  screenshotDir: "${join(dataDir, "screenshots")}"
  relay: false
`;
}

/**
 * Write the omp config overlay to `<dataDir>/omp-overlay.yml`.
 *
 * Throws if the write fails — the caller must not spawn omp without the
 * overlay because omp would fall back to its `yolo` schema default and
 * silently auto-approve all tool calls.
 *
 * @returns The absolute path to the written overlay file.
 */
export async function writeOmpOverlay(
  dataDir: string,
  resourcesPath: string,
): Promise<string> {
  const overlayPath = join(dataDir, "omp-overlay.yml");
  const yaml = buildOverlayYaml(resourcesPath, dataDir);

  // Fatal on failure — no silent fallback to yolo (plan §DX X11).
  // If writeFile throws, the error propagates to the bridge spawner which
  // must surface it to the renderer via sidecar.fatal.
  await writeFile(overlayPath, yaml, "utf8");

  return overlayPath;
}
